// Generated by tools/generate-admin-command-reference.mjs. Do not edit.
package com.aifred.admin

internal val LocalShellActions = listOf(
    RegisteredAction("local:pwd", "Local — Show the app shell working directory", "pwd", true),
    RegisteredAction("local:files", "Local — List files in the app shell working directory", "ls -la", true),
    RegisteredAction("local:storage", "Local — Show filesystem usage", "df -h", true),
    RegisteredAction("local:usage", "Local — Show the current directory size", "du -sh .", true),
    RegisteredAction("local:identity", "Local — Show the app-shell identity", "id", true),
    RegisteredAction("local:system", "Local — Show kernel and system details", "uname -a", true),
    RegisteredAction("local:processes", "Local — List processes visible to the app shell", "ps -A", true),
    RegisteredAction("local:network", "Local — Show network addresses and routes", "ip addr; ip route", true),
    RegisteredAction("local:environment", "Local — List the local process environment", "printenv | sort", true),
    RegisteredAction("termux:packages", "Local — List installed Termux packages when available", "if command -v pkg >/dev/null 2>&1; then pkg list-installed; else echo 'Termux pkg is not available'; fi", true),
    RegisteredAction("termux:info", "Local — Show Termux environment information when available", "if command -v termux-info >/dev/null 2>&1; then termux-info; else echo 'termux-info is not available'; fi", true),
    RegisteredAction("android:version", "Local — Show the Android OS version", "getprop ro.build.version.release", true),
    RegisteredAction("android:packages", "Local — List third-party Android packages visible to the app", "pm list packages -3", true),
    RegisteredAction("android:logs", "Local — Show recent logs accessible to the app", "logcat -d -t 100", true),
    RegisteredAction("site:health", "Local — Check production API health from the device", "curl -fsS https://www.north3rnlight3r.com/api/v1/health", true)
)
