"""Test skeleton for `aifred_brain.progress_memory`.

Eventually test:
- factual trend preservation
- no hidden telemetry
- approved-memory limits
- no final advice generated by Python
"""

import unittest


@unittest.skip("Skeleton only; progress memory is not implemented yet.")
class ProgressMemoryContractTests(unittest.TestCase):
    def test_progress_memory_contract_placeholder(self) -> None:
        """Placeholder for future progress memory tests."""

