"""Test skeleton for `aifred_brain.tonal_balance`.

Eventually test:
- tonal tilt
- low-mid, presence, harshness, and air evidence
- factual flags
- no final advice generated by Python
"""

import unittest


@unittest.skip("Skeleton only; tonal balance is not implemented yet.")
class TonalBalanceContractTests(unittest.TestCase):
    def test_tonal_balance_contract_placeholder(self) -> None:
        """Placeholder for future tonal balance tests."""

